spring:
  cloud:
    nacos:
      config:
        enabled: false
      discovery:
        server-addr: 127.0.0.1:8848
#  datasource:
#    url: jdbc:mysql://10.161.168.15:3306/cusoptui_dev?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
#    #    username: root
#    #    password: 123456
#    username: tkpetdev
#    password: Y4yhl9t!
#    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      #      password: redis123
      #      database: 0
      #      # 关键：禁用集群模式
  #      lettuce:
  #        cluster:
  #          enabled: true
  #        timeout: 2000ms

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: nianji-auth-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.trusted.packages: "*"

security:
  encryption:
    # 可选的全局密钥配置
    rsa-public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2KB//0QAF5XRuX9w7zZg8MmOF+1xATcBmLndKwca7vGvmW+vpqv9HIWolCdAGsKSKxw2AlJ5xuesMM0sw9W4u21oHPhUSNueZ4TtLgMEYvacr05ivGaKagEmJBT6zX2S1HvcnvJTTeJf1CofDqPLHSAWq7fAkhRdtCpHi+z21vYG2BBKTmR2yKHzdMG3WZknOC+G2jce6OhfV9JfUfCnm9D2qLgOD4BPc220Ftl8uL1KbH2D8zAgcqnINgYY8IlIXNEL8syr6pSYNBc5rxLIT24wnRyKXh/+q3B9NLXuDNf5kYrP6wB8T5mivt286t2XmhqGCuTYhhhNdtGvkjDAxwIDAQAB"
    rsa-private-key: "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDYoH//RAAXldG5f3DvNmDwyY4X7XEBNwGYud0rBxru8a+Zb6+mq/0chaiUJ0AawpIrHDYCUnnG56wwzSzD1bi7bWgc+FRI255nhO0uAwRi9pyvTmK8ZopqASYkFPrNfZLUe9ye8lNN4l/UKh8Oo8sdIBart8CSFF20KkeL7PbW9gbYEEpOZHbIofN0wbdZmSc4L4baNx7o6F9X0l9R8Keb0PaouA4PgE9zbbQW2Xy4vUpsfYPzMCByqcg2BhjwiUhc0QvyzKvqlJg0FzmvEshPbjCdHIpeH/6rcH00te4M1/mRis/rAHxPmaK+3bzq3ZeaGoYK5NiGGE120a+SMMDHAgMBAAECggEABUdb9x90FR8MfkWxvdKIaDWxJboef9YUTuFwl0TUDjCLg+Sp1hjo0RIcuod+U2icYTqNwl66IvOwSXwmdBs4JjETUWlnvGLFqGYf1XgzWioCRW9Wjpq9Ero2cLimJ+3AbzcZeDIVf5ddmHDyUswA/hOzGbofki+23NYO6kT6+t/2arWWEal155PcJrXhIBNsX7dCtn0UOskWnQW5Do7NMmhFcCbnZcLR31GpthxFu679tvhsdL+w59Znl1KLkRX0JS3sk9o7z4lBF23pZf6x4BcnV5qTZdzRhW0l+2wmSXAiIJRZEitGiwE7ZsbSeDrIIUFEoEE7jF2/TH2RA1QYyQKBgQDfreCliSjKM2FbPCMGP7Rjgpsf7NFSECIcYGtJGTJEcDuE2RS7DSz8mLGjwtBlfMSQ4gBeSaG/TjYZwj96ZwPS99ePh/0s6ICOhvLV09JwB8gr7MMM3n5Tpw7WJSXbSArb/nUPfplszHc0vc+XzQQpo9Lxn6nCtiBNsFSyhN+52wKBgQD37cCXQ/IqabA1EGEpp4Lot2bO16FRHdAi43i1CNYmtBW1te9hAkpn1ODEitxkWIyeS8oF5SoWMoIzOZCdonHdaH1zy/uh/ZRWgtKBC862aSWMV45jnrH1CWdboMYkJbc5WkMsOQ0EkR3gTApCH2l7a+BdgyNkbIj267MW4JM2hQKBgQCnxh8bav7ac6GRslC/Did7AGrkjlgPSqSbTkMKqEiJBvnN0pn3F5HnwYx0vdpcVTKHTc1i663T9ZEkzwuX/w7iPh5EvYbMGXTb8yLP+jr85wlg0Q0YaQauLj81ptV3XdkvW/Rn89iWv+Kl/71nKlL1/LhrngvSTZN7UkilQn8hQwKBgQDZVs+NCyBAM/QnIFu8sz7cGOKEEp00ycjKvNP1B3EL7rRVXc8iIGrviLsdMImxYbqrjc7kyhbR7KcclqsCtQPSTyYim7/UKsKd8ALu41XrrFMhKyQEinqATyUPOupXh8SN/2WBX+XcigZBuQcJHhZO/qtp7mrZPxf2NXsCZA5JLQKBgHFhTSI3neRI6+m0j3yCtDtp4fa45dVl2aTWPbvzJssV5UslEsCYEGCw4JX4o8x3OPyswMmZlDv32HnP0DqMBHfV6hWMJpZGc3+khv4wWAozOPwbQP4LHb0tre4hyzKlEO/o/9O5wccgI/LGISmba9XvvYzGtk1aRg0FOppUd63o"
    aes-key: "SNprGQi/tMdyK2QqSmSPVZlWS8HRwCOjnRz0JWL0iR4="
