singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: tkoP_12345
  subscriptionsPerConnection: 5
  clientName: h5cc_redis
  address: "redis://10.160.161.140:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 24
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
threads: 16
nettyThreads: 32
codec:
  class: org.redisson.codec.JsonJacksonCodec
transportMode: "NIO"