spring:
  cloud:
    nacos:
      config:
        enabled: false
      discovery:
        server-addr: 127.0.0.1:8848
  #  datasource:
  #    url: jdbc:mysql://10.161.168.15:3306/cusoptui_dev?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
  #    #    username: root
  #    #    password: 123456
  #    username: tkpetdev
  #    password: Y4yhl9t!
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      #      password: redis123
      #      database: 0
      #      # 关键：禁用集群模式
  #      lettuce:
  #        cluster:
  #          enabled: true
  #        timeout: 2000ms

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: nianji-auth-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.trusted.packages: "*"
